### PR TITLE
U nets

### PR DESCRIPTION
**Pull request by constantinpape**
Adds 2d, 2p5d and 3d u-net models.

### CODE REVIEW

**Comment by nasimrahaman** [comment]
Alright, two points: 
* We need an `__init__.py` in `neurofire/neurofire/models`.
* A directory of models would be nice to have. So we could put e.g. `model: 'UNet2D'` in a config file, and just do `model = models.get_model(config['model'])(**config['model_kwargs'])` to build the model. That way, any changes in the model between two or more experiments can be summarized by diff'ing the config files.

**Comment by constantinpape** [comment]
If I understand you correctly you want an `__init__.py` in the models ordner that looks like this:

```
from .cantor.cantor import Cantor
from .unets.unet_2d import Unet2D
# etc. for 2p5d and 3d unet

def get_model(name):
    assert name in globals(), "Model not found."
return globals().get(name)
```

No problem, I can add this.
The only remaining question is, if we should leave the duplicated functionality in the 
submodule inits, here

https://github.com/inferno-pytorch/neurofire/blob/u-nets/neurofire/models/unet/__init__.py

and here:

https://github.com/inferno-pytorch/neurofire/blob/u-nets/neurofire/models/cantor/__init__.py

I would argue to remove it and only have it on the `models` level.

**Comment by nasimrahaman** [comment]
Agreed. 👍

**Comment by constantinpape** [comment]
Updated the PR with the requested changes in 
https://github.com/inferno-pytorch/neurofire/blob/u-nets/neurofire/models/__init__.py

**Comment by nasimrahaman** [comment]
Me gusta.

**Pull request merged**
